name: Deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node version 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Get Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache Dependencies
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install --frozen-lockfile --colors

      - name: Build
        run: yarn build --colors

      - name: Cache Firebase
        uses: actions/cache@v1
        id: firebase-cache
        with:
          path: ./.firebase
          key: ${{ runner.os }}-firebase

      - name: Deploy to Firebase
        run: yarn firebase:deploy --project cephalon-tobran --non-interactive
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
