name: Pull Request Title

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened

jobs:
  title:
    name: Lint Title
    runs-on: ubuntu-latest

    steps:
      - name: Lint Pull Request Title
        uses: amannn/action-semantic-pull-request@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
