name: Release

on:
  push:
    branches:
      - master

    paths-ignore:
      - ".*/**"
      - "!.github/workflows/release.yaml"
      - "CHANGELOG.md"
      - "package.json"

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node version 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Get Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache Dependencies
        uses: actions/cache@v1
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install --frozen-lockfile --colors

      - name: Lint
        run: yarn lint --no-fix --colors

      - name: Unit Test
        run: yarn test:unit --collectCoverage --ci --colors

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v2.1.0
        with:
          git_user_signingkey: true
          git_commit_gpgsign: true
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Semantic Release
        run: yarn release --colors
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          GIT_AUTHOR_NAME: Cephalon Tobran
          GIT_AUTHOR_EMAIL: tobran@cephalon-tobran
          GIT_COMMITTER_NAME: Cephalon Tobran
          GIT_COMMITTER_EMAIL: tobran@cephalon-tobran
